// 由 scripts/gen_styles_data.py 從《300+电影风格提示词.csv》生成，勿手改。
// 來源：/Users/yinweiqi/Desktop/人物卡 2/分镜运镜提示词＋AI指令整理/分镜提示词合集/300+电影风格提示词.csv
const STYLE_CATEGORIES = [
  {
    "id": "film",
    "label": "影視風格",
    "targetField": "style"
  },
  {
    "id": "texture",
    "label": "畫面質感",
    "targetField": "style"
  },
  {
    "id": "light",
    "label": "燈光色調",
    "targetField": "light"
  },
  {
    "id": "camera",
    "label": "攝影手法",
    "targetField": "camera"
  },
  {
    "id": "platform",
    "label": "平台風格",
    "targetField": "style"
  }
];

const CINEMATIC_STYLES = [
  { id: 'ST001', category: 'film', text: "王家卫电影风格：慢镜头+模糊边缘+饱和色彩" },
  { id: 'ST002', category: 'film', text: "诺兰式倒叙结构：非线性时间轴+暗色调" },
  { id: 'ST003', category: 'film', text: "黑泽明剧场感：高反差黑白影调+固定机位" },
  { id: 'ST004', category: 'film', text: "港片光影风格：霓虹反光+快速切换镜头" },
  { id: 'ST005', category: 'film', text: "韩剧慢镜头浪漫：柔光+背景虚化+配乐旋律" },
  { id: 'ST006', category: 'film', text: "宫崎骏动画感：自然色彩+清新构图+手绘质感" },
  { id: 'ST007', category: 'film', text: "漫威大片感：大场景+爆炸特效+CG合成" },
  { id: 'ST008', category: 'film', text: "皮克斯动画质感：明亮色彩+卡通建模+情感流动" },
  { id: 'ST009', category: 'film', text: "张艺谋色彩对比风格：红绿对撞+对称构图" },
  { id: 'ST010', category: 'film', text: "李安东方写实风：自然光线+内敛情绪" },
  { id: 'ST011', category: 'film', text: "西部片风格：荒漠远景+冷暖对比+低角度" },
  { id: 'ST012', category: 'film', text: "法式文艺风：碎片叙事+自然光影+低饱和" },
  { id: 'ST013', category: 'film', text: "纪录片感：自然光+镜头抖动+真实色调" },
  { id: 'ST014', category: 'film', text: "港风怀旧感：黄色滤镜+慢动作走位" },
  { id: 'ST015', category: 'film', text: "黑色电影风格：强光阴影+硬汉独白+反光雨夜" },
  { id: 'ST016', category: 'film', text: "美式青春片风格：明快节奏+活力色彩" },
  { id: 'ST017', category: 'film', text: "印度歌舞片风格：高饱和+快速剪辑+群舞镜头" },
  { id: 'ST018', category: 'film', text: "欧洲冷感系：灰白色调+极简构图" },
  { id: 'ST019', category: 'film', text: "BBC纪录片感：精致构图+慢推镜头+旁白配音" },
  { id: 'ST020', category: 'film', text: "Netflix惊悚剧风格：低光源+突变音效+细节特写" },
  { id: 'ST021', category: 'texture', text: "胶片颗粒感+复古色调" },
  { id: 'ST022', category: 'texture', text: "VHS旧录像风+画面噪点" },
  { id: 'ST023', category: 'texture', text: "高清8K画质+锐化边缘" },
  { id: 'ST024', category: 'texture', text: "油画风滤镜+厚重笔触感" },
  { id: 'ST025', category: 'texture', text: "水彩柔焦画感+手绘轮廓" },
  { id: 'ST026', category: 'texture', text: "赛博朋克噪点+冷紫蓝色调" },
  { id: 'ST027', category: 'texture', text: "黑白极简质感+强光阴影" },
  { id: 'ST028', category: 'texture', text: "HDR高动态对比+金属质感" },
  { id: 'ST029', category: 'texture', text: "质感磨砂风格+柔光过渡" },
  { id: 'ST030', category: 'texture', text: "蜡笔涂抹风格+颜色跳跃" },
  { id: 'ST031', category: 'texture', text: "金属银灰画面+冰冷质感" },
  { id: 'ST032', category: 'texture', text: "潮流闪烁画质+霓虹叠影" },
  { id: 'ST033', category: 'texture', text: "木刻风风格+线条粗糙感" },
  { id: 'ST034', category: 'texture', text: "像素马赛克风+90年代风情" },
  { id: 'ST035', category: 'texture', text: "胶片曝光风格+色彩晕染" },
  { id: 'ST036', category: 'texture', text: "梦幻画质+光斑散射效果" },
  { id: 'ST037', category: 'texture', text: "质感磨皮处理+奶油柔光" },
  { id: 'ST038', category: 'texture', text: "工业风画质+灰色调颗粒" },
  { id: 'ST039', category: 'texture', text: "超现实清晰风+异化边缘" },
  { id: 'ST040', category: 'texture', text: "复古明信片风+褪色怀旧" },
  { id: 'ST041', category: 'light', text: "霓虹灯+紫蓝色冷调" },
  { id: 'ST042', category: 'light', text: "日出金光+橙红过渡" },
  { id: 'ST043', category: 'light', text: "阴雨天蓝灰色+湿润反光" },
  { id: 'ST044', category: 'light', text: "清晨自然光+低对比" },
  { id: 'ST045', category: 'light', text: "黄昏暖光+柔和高光" },
  { id: 'ST046', category: 'light', text: "夜景灯火辉煌+反光地面" },
  { id: 'ST047', category: 'light', text: "车灯反射+都市光污染" },
  { id: 'ST048', category: 'light', text: "工业冷光+白蓝高亮" },
  { id: 'ST049', category: 'light', text: "蜡烛光源+暖色微光" },
  { id: 'ST050', category: 'light', text: "金属质感灯光+蓝紫边缘光" },
  { id: 'ST051', category: 'light', text: "摄影棚高反差灯光+全白背景" },
  { id: 'ST052', category: 'light', text: "窗户光影+植物投影" },
  { id: 'ST053', category: 'light', text: "教堂彩色玻璃光+斑斓光斑" },
  { id: 'ST054', category: 'light', text: "落日逆光+眩光高反差" },
  { id: 'ST055', category: 'light', text: "办公室荧光灯+冷白打光" },
  { id: 'ST056', category: 'light', text: "舞台聚光灯+色彩切换" },
  { id: 'ST057', category: 'light', text: "水底反光+斑驳波纹" },
  { id: 'ST058', category: 'light', text: "森林穿透光+轻微雾气" },
  { id: 'ST059', category: 'light', text: "火焰照明+动态闪烁" },
  { id: 'ST060', category: 'light', text: "天光洒落+反光纸折射" },
  { id: 'ST061', category: 'camera', text: "手持镜头+轻微晃动" },
  { id: 'ST062', category: 'camera', text: "航拍鸟瞰+大场景过渡" },
  { id: 'ST063', category: 'camera', text: "第一人称POV+真实体验" },
  { id: 'ST064', category: 'camera', text: "转场模糊拉动+快速推镜" },
  { id: 'ST065', category: 'camera', text: "定格拍摄+帧率降低" },
  { id: 'ST066', category: 'camera', text: "慢动作特写+延时轨迹" },
  { id: 'ST067', category: 'camera', text: "拉近面部镜头+情绪捕捉" },
  { id: 'ST068', category: 'camera', text: "360环绕镜头+情绪包围" },
  { id: 'ST069', category: 'camera', text: "滑轨平移镜头+画面稳定" },
  { id: 'ST070', category: 'camera', text: "无人机追拍+城市视角" },
  { id: 'ST071', category: 'camera', text: "双人跟随视角+同步镜头" },
  { id: 'ST072', category: 'camera', text: "镜头推进+背景虚化" },
  { id: 'ST073', category: 'camera', text: "过肩视角+对话感增强" },
  { id: 'ST074', category: 'camera', text: "反打镜头+情绪衔接" },
  { id: 'ST075', category: 'camera', text: "动态变焦+节奏感镜头" },
  { id: 'ST076', category: 'camera', text: "快速摇摄+混乱节奏" },
  { id: 'ST077', category: 'camera', text: "切换视角+主客交错" },
  { id: 'ST078', category: 'camera', text: "定格动画风+逐帧展示" },
  { id: 'ST079', category: 'camera', text: "近景切换+视觉聚焦" },
  { id: 'ST080', category: 'camera', text: "分屏并列镜头+对比叙事" },
  { id: 'ST081', category: 'platform', text: "小红书爆款视频风格+淡粉色调+卡点剪辑" },
  { id: 'ST082', category: 'platform', text: "抖音人物特写+动感音乐+BGM加速感" },
  { id: 'ST083', category: 'platform', text: "Tiktok变装卡点视频+滤镜变化节奏快" },
  { id: 'ST084', category: 'platform', text: "Instagram美妆风+柔焦+打光精准" },
  { id: 'ST085', category: 'platform', text: "Youtube vlog叙事风格+头戴GoPro视角" },
  { id: 'ST086', category: 'platform', text: "Bilibili二次元UP主风格+卡点特效+字幕跟随" },
  { id: 'ST087', category: 'platform', text: "品牌广告包装风+高饱和+字幕边框" },
  { id: 'ST088', category: 'platform', text: "电商短视频展示风+产品放大+定格+箭头" },
  { id: 'ST089', category: 'platform', text: "电视剧片头风+慢入+角色介绍文字" },
  { id: 'ST090', category: 'platform', text: "美食探店视频风+俯拍+特写+切换节奏快" },
  { id: 'ST091', category: 'platform', text: "种草安利类视频风+试用+测评+弹幕感" },
  { id: 'ST092', category: 'platform', text: "旅游纪实视频风+延时摄影+广角城市" },
  { id: 'ST093', category: 'platform', text: "影视混剪视频风格+黑白慢镜+叠化闪回" },
  { id: 'ST094', category: 'platform', text: "企业宣传片风格+清晰LOGO+蓝白基调" },
  { id: 'ST095', category: 'platform', text: "综艺感预热视频+人物边框+闪动字幕" },
  { id: 'ST096', category: 'platform', text: "AI换脸短视频风+脸部匹配+跳剪接" },
  { id: 'ST097', category: 'platform', text: "游戏混剪风格+高对比度+视角切换" },
  { id: 'ST098', category: 'platform', text: "情绪类视频风格+音乐主导+极简构图" },
  { id: 'ST099', category: 'platform', text: "萌宠短视频风格+圆头滤镜+字幕卡通" },
  { id: 'ST100', category: 'platform', text: "运动训练风格+高帧率+慢放动作+咔咔声效" },
  { id: 'ST101', category: 'film', text: "纪录片手持风格：真实环境光+轻微镜头晃动" },
  { id: 'ST102', category: 'film', text: "浪漫主义镜头：柔光+色彩渐变+慢速推镜" },
  { id: 'ST103', category: 'film', text: "新浪潮电影风格：突兀剪辑+非逻辑叙事" },
  { id: 'ST104', category: 'film', text: "荒诞剧风格：怪异构图+夸张表演+低饱和" },
  { id: 'ST105', category: 'film', text: "剧场舞台风：静态构图+中心打光+对称" },
  { id: 'ST106', category: 'film', text: "反乌托邦电影风格：灰蓝色调+压抑空间" },
  { id: 'ST107', category: 'film', text: "80年代美剧风：颗粒感+怀旧音乐+大字体标题" },
  { id: 'ST108', category: 'film', text: "90年代偶像剧风格：柔焦+梦幻滤镜+夸张表情" },
  { id: 'ST109', category: 'film', text: "警匪片风格：紧张节奏+追逐镜头+低光场景" },
  { id: 'ST110', category: 'film', text: "校园青春风格：明亮色彩+对称构图+轻音乐" },
  { id: 'ST111', category: 'film', text: "灾难电影风格：剧烈晃动+闪回叠化+广角特写" },
  { id: 'ST112', category: 'film', text: "科幻实验片风格：霓虹光+深色调+镜面反射" },
  { id: 'ST113', category: 'film', text: "舞台剧改编影像风：高对比黑白+台词为主" },
  { id: 'ST114', category: 'film', text: "宗教主题风格：庄严色调+静态构图" },
  { id: 'ST115', category: 'film', text: "现实主义电影风格：自然光+非演员+长镜头" },
  { id: 'ST116', category: 'film', text: "心理惊悚片风格：镜头错位+昏暗光影+变焦特写" },
  { id: 'ST117', category: 'film', text: "城市犯罪片风：夜景霓虹+快节奏剪辑" },
  { id: 'ST118', category: 'film', text: "民族文化电影风格：传统服饰+地方音乐+自然环境" },
  { id: 'ST119', category: 'film', text: "未来科幻风格：金属感强+HUD叠加界面" },
  { id: 'ST120', category: 'film', text: "复仇主题风格：慢镜头+阴郁配乐+特写眼神" },
  { id: 'ST121', category: 'texture', text: "流光质感+边缘炫光" },
  { id: 'ST122', category: 'texture', text: "漫画描边风格+黑白分明" },
  { id: 'ST123', category: 'texture', text: "低像素风格+8bit配色" },
  { id: 'ST124', category: 'texture', text: "牛皮纸质感+褪色画面" },
  { id: 'ST125', category: 'texture', text: "镜头泛黄质感+老胶片感" },
  { id: 'ST126', category: 'texture', text: "瓷砖反光质感+干净利落" },
  { id: 'ST127', category: 'texture', text: "刺绣线条风+平面化构图" },
  { id: 'ST128', category: 'texture', text: "金粉颗粒质感+梦幻模糊" },
  { id: 'ST129', category: 'texture', text: "火焰特效质感+橙红过渡" },
  { id: 'ST130', category: 'texture', text: "蓝色液态质感+流体转场" },
  { id: 'ST131', category: 'texture', text: "裂纹屏幕风+数字失真" },
  { id: 'ST132', category: 'texture', text: "雾面柔化质感+水汽遮挡" },
  { id: 'ST133', category: 'texture', text: "玻璃碎片纹理+冷色透明" },
  { id: 'ST134', category: 'texture', text: "科幻HUD质感+绿色扫描" },
  { id: 'ST135', category: 'texture', text: "网格结构质感+结构线条" },
  { id: 'ST136', category: 'texture', text: "纹理强化风格+粗糙画布" },
  { id: 'ST137', category: 'texture', text: "金属腐蚀感+工业废墟风" },
  { id: 'ST138', category: 'texture', text: "浓重素描风格+笔触交叠" },
  { id: 'ST139', category: 'texture', text: "梦中虚幻画质+模糊景深" },
  { id: 'ST140', category: 'texture', text: "霓虹倒影质感+街道水渍" },
  { id: 'ST141', category: 'light', text: "青蓝夜色调+冷感氛围" },
  { id: 'ST142', category: 'light', text: "玫瑰粉柔光+少女滤镜" },
  { id: 'ST143', category: 'light', text: "绿色实验室灯+不安感" },
  { id: 'ST144', category: 'light', text: "红蓝警灯交替闪烁" },
  { id: 'ST145', category: 'light', text: "橘黄拂晓光线+暖意渐入" },
  { id: 'ST146', category: 'light', text: "炽白阳光逆光拍摄" },
  { id: 'ST147', category: 'light', text: "黄绿森林光+斑驳树影" },
  { id: 'ST148', category: 'light', text: "紫色舞台灯+跳跃感" },
  { id: 'ST149', category: 'light', text: "火光照明+动态色温变化" },
  { id: 'ST150', category: 'light', text: "闪电亮光+黑白分明" },
  { id: 'ST151', category: 'light', text: "车窗倒影灯+彩色动感" },
  { id: 'ST152', category: 'light', text: "工业吊灯影+墙面长影" },
  { id: 'ST153', category: 'light', text: "晨曦薄雾光+柔和无边界" },
  { id: 'ST154', category: 'light', text: "窗边午后光+纸张飞舞" },
  { id: 'ST155', category: 'light', text: "隧道低光照明+局部强光" },
  { id: 'ST156', category: 'light', text: "教室日落光+金边发丝" },
  { id: 'ST157', category: 'light', text: "高对比楼梯灯光+强影投射" },
  { id: 'ST158', category: 'light', text: "夜色河畔灯光+折射波纹" },
  { id: 'ST159', category: 'light', text: "货架上方灯+商品反光高光" },
  { id: 'ST160', category: 'light', text: "电影院投影灯+粒子漂浮" },
  { id: 'ST161', category: 'camera', text: "超广角镜头拉伸感+透视极强" },
  { id: 'ST162', category: 'camera', text: "低机位仰拍+人物高大化" },
  { id: 'ST163', category: 'camera', text: "镜头虚焦切换+情绪递进" },
  { id: 'ST164', category: 'camera', text: "镜头推拉交替+混乱感增强" },
  { id: 'ST165', category: 'camera', text: "倒放镜头+时间回溯" },
  { id: 'ST166', category: 'camera', text: "交叉剪辑+不同时间线融合" },
  { id: 'ST167', category: 'camera', text: "镜头隐藏过渡+遮挡转场" },
  { id: 'ST168', category: 'camera', text: "渐显过度+光晕亮起" },
  { id: 'ST169', category: 'camera', text: "拉远切黑+暗示场景结束" },
  { id: 'ST170', category: 'camera', text: "慢拉近嘴角微笑+强化情绪" },
  { id: 'ST171', category: 'camera', text: "反光转场+镜面滑动" },
  { id: 'ST172', category: 'camera', text: "水面倒影接镜头+上下反转" },
  { id: 'ST173', category: 'camera', text: "分层镜头语言+远中近同时推进" },
  { id: 'ST174', category: 'camera', text: "主观镜头中插手部特写" },
  { id: 'ST175', category: 'camera', text: "慢变焦压缩空间+心理压迫" },
  { id: 'ST176', category: 'camera', text: "偏移构图+画面不稳定感" },
  { id: 'ST177', category: 'camera', text: "直线拉动轨道感+强烈动感" },
  { id: 'ST178', category: 'camera', text: "角色遮挡快速切换+节奏强" },
  { id: 'ST179', category: 'camera', text: "镜头穿墙接空间+无缝变化" },
  { id: 'ST180', category: 'camera', text: "边缘暗角镜头+集中焦点" },
  { id: 'ST181', category: 'platform', text: "小红书情绪配文风格+细文字+背景虚焦" },
  { id: 'ST182', category: 'platform', text: "抖音挑战赛卡点风+快剪+特效音符" },
  { id: 'ST183', category: 'platform', text: "Tiktok换装循环剪辑+对比前后" },
  { id: 'ST184', category: 'platform', text: "Youtube长篇Vlog风+节奏轻松+真实语音" },
  { id: 'ST185', category: 'platform', text: "淘宝商品讲解风+放大展示+解说口播" },
  { id: 'ST186', category: 'platform', text: "B站二创视频风格+搞笑剪辑+表情包" },
  { id: 'ST187', category: 'platform', text: "Instagram生活记录风+滤镜轻暖+低饱和" },
  { id: 'ST188', category: 'platform', text: "TVC广告感视频风+LOGO飞入+镜头干净" },
  { id: 'ST189', category: 'platform', text: "短剧热剧预告风+闪回+字幕压场" },
  { id: 'ST190', category: 'platform', text: "汽车测评视频风+低角度跟拍+引擎声同步" },
  { id: 'ST191', category: 'platform', text: "教育讲解视频风+白底+手势板书" },
  { id: 'ST192', category: 'platform', text: "知识类爆款短视频风+快语音+图文混剪" },
  { id: 'ST193', category: 'platform', text: "品牌预热视频风+慢推+标语字幕" },
  { id: 'ST194', category: 'platform', text: "抖音剧情反转类短剧风+黑白分隔镜头" },
  { id: 'ST195', category: 'platform', text: "商拍场景风+构图考究+产品核心突出" },
  { id: 'ST196', category: 'platform', text: "节日祝福类视频风+模板切换+庆祝音乐" },
  { id: 'ST197', category: 'platform', text: "科普动画视频风格+拟人+小人插图" },
  { id: 'ST198', category: 'platform', text: "悬疑剧情感风格+偏冷色+叠化闪现" },
  { id: 'ST199', category: 'platform', text: "宠物搞笑混剪风格+变声+字幕突出" },
  { id: 'ST200', category: 'platform', text: "街头采访短视频风格+字幕飞入+环境声真实" },
  { id: 'ST201', category: 'film', text: "青春日剧风格：清淡色调+浅景深+柔和光线" },
  { id: 'ST202', category: 'film', text: "英伦剧情风格：暗色复古+室内烛光+对称构图" },
  { id: 'ST203', category: 'film', text: "战地纪实风格：手持抖动+高对比+爆炸环境" },
  { id: 'ST204', category: 'film', text: "赛博东亚风：汉字霓虹+摩天楼林立+杂乱城市" },
  { id: 'ST205', category: 'film', text: "欧美独立电影风：低饱和+空镜+叙事碎片化" },
  { id: 'ST206', category: 'film', text: "短剧穿越风格：古今混搭+快速变装+场景拼接" },
  { id: 'ST207', category: 'film', text: "荒野生存剧风：自然光+环境音强+沉浸追随" },
  { id: 'ST208', category: 'film', text: "法语爱情片风格：长镜+低语对白+街拍质感" },
  { id: 'ST209', category: 'film', text: "恐怖片风格：压暗光线+突变音效+主观镜头" },
  { id: 'ST210', category: 'film', text: "真人童话风格：饱和梦境色+慢节奏" },
  { id: 'ST211', category: 'film', text: "末世电影风格：破败城市+灰黄色调+广角" },
  { id: 'ST212', category: 'film', text: "谍战片风格：暗房+电话亭+帽子眼神特写" },
  { id: 'ST213', category: 'film', text: "俄式冷战风格：蓝灰调+低色温+大量字幕叠加" },
  { id: 'ST214', category: 'film', text: "童年回忆片风格：黄调复古+慢镜头+自然音效" },
  { id: 'ST215', category: 'film', text: "警探剧风格：玻璃写字板+白板推理+悬疑配乐" },
  { id: 'ST216', category: 'film', text: "玄幻国风片：飘带+云雾特效+红青对撞" },
  { id: 'ST217', category: 'film', text: "罪案还原剧风：现场还原+旁白+模糊人物" },
  { id: 'ST218', category: 'film', text: "日式深夜剧风格：微光环境+封闭空间+吃饭动作" },
  { id: 'ST219', category: 'film', text: "末日旅人风格：破败+独行+极简对话" },
  { id: 'ST220', category: 'film', text: "希区柯克悬疑风：固定机位+交替剪辑+低音乐" },
  { id: 'ST221', category: 'texture', text: "压印纹理+棉纸肌理" },
  { id: 'ST222', category: 'texture', text: "水墨扩散风格+柔化边界" },
  { id: 'ST223', category: 'texture', text: "玻璃磨砂感+模糊斑点" },
  { id: 'ST224', category: 'texture', text: "瓷砖蓝调反射+边角清晰" },
  { id: 'ST225', category: 'texture', text: "折纸层叠感+立体分割" },
  { id: 'ST226', category: 'texture', text: "幻彩渐变光+反射折射感" },
  { id: 'ST227', category: 'texture', text: "编织纹理感+纸织视觉" },
  { id: 'ST228', category: 'texture', text: "彩笔涂鸦风格+边缘跳色" },
  { id: 'ST229', category: 'texture', text: "霓虹重影画质+偏色模糊" },
  { id: 'ST230', category: 'texture', text: "古画纸本感+斑驳色块" },
  { id: 'ST231', category: 'texture', text: "石头裂纹风格+硬边界感" },
  { id: 'ST232', category: 'texture', text: "数字虚焦风+像素模糊融合" },
  { id: 'ST233', category: 'texture', text: "海报风构图+边框和笔触" },
  { id: 'ST234', category: 'texture', text: "铁锈斑驳感+工业老旧" },
  { id: 'ST235', category: 'texture', text: "亚克力质感+高光透亮" },
  { id: 'ST236', category: 'texture', text: "指纹涂抹风格+残缺边缘" },
  { id: 'ST237', category: 'texture', text: "布料纹理感+轻柔颗粒" },
  { id: 'ST238', category: 'texture', text: "星轨叠加质感+动态光纹" },
  { id: 'ST239', category: 'texture', text: "陶瓷釉面质感+清亮饱和" },
  { id: 'ST240', category: 'texture', text: "闪粉质感+舞台背景感" },
  { id: 'ST241', category: 'light', text: "湖边日落金黄光+水波反射" },
  { id: 'ST242', category: 'light', text: "工地夜间强光+强烈阴影" },
  { id: 'ST243', category: 'light', text: "天台霓虹光+人物剪影" },
  { id: 'ST244', category: 'light', text: "红色信号灯+慢节奏光影" },
  { id: 'ST245', category: 'light', text: "彩带反射光+运动虚化" },
  { id: 'ST246', category: 'light', text: "警示灯旋转闪烁+黑背景" },
  { id: 'ST247', category: 'light', text: "月光打脸侧光+蓝色主调" },
  { id: 'ST248', category: 'light', text: "公交夜景外射灯+窗户投影" },
  { id: 'ST249', category: 'light', text: "节日彩灯混色+跳动频率" },
  { id: 'ST250', category: 'light', text: "照相机闪光灯+画面爆白" },
  { id: 'ST251', category: 'light', text: "激光灯横扫+舞台感强" },
  { id: 'ST252', category: 'light', text: "绿植下散射光+柔焦+自然" },
  { id: 'ST253', category: 'light', text: "高光阴影交替灯光+强结构" },
  { id: 'ST254', category: 'light', text: "信号灯三色跳变+场景定格" },
  { id: 'ST255', category: 'light', text: "落地灯光环+暖色渐变" },
  { id: 'ST256', category: 'light', text: "热带阳光硬打光+清晰投影" },
  { id: 'ST257', category: 'light', text: "仓库天窗光柱+尘埃可见" },
  { id: 'ST258', category: 'light', text: "隧道尾光+暗部拖影" },
  { id: 'ST259', category: 'light', text: "地铁车厢荧光灯+人物打亮" },
  { id: 'ST260', category: 'light', text: "办公室投影灯打脸+背面阴影" },
  { id: 'ST261', category: 'camera', text: "建筑穿越镜头+楼层不断切换" },
  { id: 'ST262', category: 'camera', text: "倒地视角拍摄+倒影突出" },
  { id: 'ST263', category: 'camera', text: "车内后视镜镜头+人物交替露出" },
  { id: 'ST264', category: 'camera', text: "快速镜头推进+情绪高涨" },
  { id: 'ST265', category: 'camera', text: "过场黑屏节奏+音效匹配" },
  { id: 'ST266', category: 'camera', text: "全景叠化转场+人物定格" },
  { id: 'ST267', category: 'camera', text: "正上方旋转俯拍+集体行为聚焦" },
  { id: 'ST268', category: 'camera', text: "环绕定焦变景深+人静背景变" },
  { id: 'ST269', category: 'camera', text: "镜头从布帘中探出+渐显角色" },
  { id: 'ST270', category: 'camera', text: "走廊延伸镜头+推入紧张空间" },
  { id: 'ST271', category: 'camera', text: "俯冲镜头+快速压迫感" },
  { id: 'ST272', category: 'camera', text: "水下仰拍+气泡动态" },
  { id: 'ST273', category: 'camera', text: "地面跟拍奔跑动作+碎石飞溅" },
  { id: 'ST274', category: 'camera', text: "突然抬镜头+人物遮光进入" },
  { id: 'ST275', category: 'camera', text: "镜头切近+表情震颤细节" },
  { id: 'ST276', category: 'camera', text: "倒置还原镜头+画面旋转配乐" },
  { id: 'ST277', category: 'camera', text: "爆炸慢速推进+人物背影对光" },
  { id: 'ST278', category: 'camera', text: "纵深切换+长走廊时间错觉" },
  { id: 'ST279', category: 'camera', text: "倒放+物体回收特写" },
  { id: 'ST280', category: 'camera', text: "转场碰撞剪辑+冲击配乐" },
  { id: 'ST281', category: 'platform', text: "短剧竖屏分镜感+人物遮挡切换" },
  { id: 'ST282', category: 'platform', text: "小红书滤镜测评风+左右对比" },
  { id: 'ST283', category: 'platform', text: "抖音美妆三连展示+卡点特写" },
  { id: 'ST284', category: 'platform', text: "Tiktok人物定格变装+三段结构" },
  { id: 'ST285', category: 'platform', text: "B站语录混剪风+情绪带字幕" },
  { id: 'ST286', category: 'platform', text: "品牌口播广告+LOGO落版+快节奏" },
  { id: 'ST287', category: 'platform', text: "长篇Vlog节奏剪+旅拍配音" },
  { id: 'ST288', category: 'platform', text: "电影解说短视频风+画外音+字幕分段" },
  { id: 'ST289', category: 'platform', text: "学习类竖屏快语速+图表飞入" },
  { id: 'ST290', category: 'platform', text: "生活日常安静风+自然光+ASMR音效" },
  { id: 'ST291', category: 'platform', text: "宠物拟人化配音视频+弹幕感字幕" },
  { id: 'ST292', category: 'platform', text: "短视频动画转绘风格+漫画风镜头" },
  { id: 'ST293', category: 'platform', text: "AI换装视频风+模型切换+镜头定格" },
  { id: 'ST294', category: 'platform', text: "产品对比实测视频风+标签标尺" },
  { id: 'ST295', category: 'platform', text: "情侣反应类视频风+多角度切换" },
  { id: 'ST296', category: 'platform', text: "街头实拍互动视频+人物突入+快剪" },
  { id: 'ST297', category: 'platform', text: "拆箱评测视频风+缓慢开盒+局部特写" },
  { id: 'ST298', category: 'platform', text: "短剧类角色台词字幕+表情突出" },
  { id: 'ST299', category: 'platform', text: "新闻速览类视频风+拼贴画面+高音效节奏" },
  { id: 'ST300', category: 'platform', text: "短篇纪录类风格+慢镜长景+自然环境音" }
];

export { STYLE_CATEGORIES, CINEMATIC_STYLES };
